# PARA LA PRIMER COLUMNA

In [1]:
function first_Column(f::Function,a,b,n)
    #a-límite inferior, b-límite inferior, n-número de intervalo
    
    matrix=zeros(n,n)
    #creación de una matriz cuadrada
    
    matrix[1,1]=((b-a)/(2))*(f(a)+f(b))
    #para el elemento (1,1) de la matriz aplicamos la integral del trapecio
    
    for k in 2:n             
        LIM_SUM=(2^(k-2)) #para cada elemento (n,1) definimos un límite para la suma
        h=(b-a)/(2^(k-2)) #para cada elemento(n,1) definimos una h
        sum=0.0
        for i in 1:LIM_SUM
            sum=sum+h*(f(a+(i-(1/2))*h))
        end
        integral=(1/2)*(matrix[k-1,1]+sum)
        matrix[k,1]=integral
    end
    matrix
end


first_Column (generic function with 1 method)

In [2]:
first_Column(x->sin(x),0,pi,6)

6×6 Array{Float64,2}:
 1.92367e-16  0.0  0.0  0.0  0.0  0.0
 1.5708       0.0  0.0  0.0  0.0  0.0
 1.89612      0.0  0.0  0.0  0.0  0.0
 1.97423      0.0  0.0  0.0  0.0  0.0
 1.99357      0.0  0.0  0.0  0.0  0.0
 1.99839      0.0  0.0  0.0  0.0  0.0

# Pasando a los siguientes niveles

In [3]:
function romberg_Integration(f::Function,a,b,n)
    matrix=zeros(n,n)
    #creación de una matriz cuadrada
    
    matrix[1,1]=((b-a)/(2))*(f(a)+f(b))
    #para el elemento (1,1) de la matriz aplicamos la integral del trapecio
    
    for k in 2:n             
        LIM_SUM=(2^(k-2)) #para cada elemento (n,1) definimos un límite para la suma
        h=(b-a)/(2^(k-2)) #para cada elemento(n,1) definimos una h
        sum=0.0
        for i in 1:LIM_SUM
            sum=sum+h*(f(a+(i-(1/2))*h))
        end
        integral=(1/2)*(matrix[k-1,1]+sum)
        matrix[k,1]=integral
    end
    matrix
    
    #Para pasar al segundo nivel, (COLUMA 2)
    for j in 2:n
        
        #Debe empezar en los elemento de la matriz i=j
        for i in j:n
            aproximation=((4^(j-1))*(matrix[i,j-1])-(matrix[i-1,j-1]))/((4^(j-1)-1))
            
            #Se almacenarán todos los elementos de la columna.
            matrix[i,j]=aproximation
        end
    end
    matrix
end
            

romberg_Integration (generic function with 1 method)

# Ejemplo 1

In [4]:
romberg_Integration(x->sin(x),0,pi,6)

6×6 Array{Float64,2}:
 1.92367e-16  0.0      0.0      0.0      0.0  0.0
 1.5708       2.0944   0.0      0.0      0.0  0.0
 1.89612      2.00456  1.99857  0.0      0.0  0.0
 1.97423      2.00027  1.99998  2.00001  0.0  0.0
 1.99357      2.00002  2.0      2.0      2.0  0.0
 1.99839      2.0      2.0      2.0      2.0  2.0

# Ejemplo 2

In [5]:
romberg_Integration(x->1/x,1,3,3)

3×3 Array{Float64,2}:
 1.33333  0.0      0.0    
 1.16667  1.11111  0.0    
 1.11667  1.1      1.09926

# Ejemplo 3

In [6]:
romberg_Integration(x->x*sqrt(complex(1+x^2)),0,3,3)

3×3 Array{Float64,2}:
 14.2302   0.0      0.0   
 11.1714  10.1517   0.0   
 10.4438  10.2013  10.2046